CREATE TABLE IF NOT EXISTS accounts (
    id INT NOT NULL AUTO_INCREMENT,
    email VARCHAR(100) NOT NULL, 
    username VARCHAR(30) NOT NULL,
    password VARCHAR(60) NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_online BOOLEAN NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE (email, username)
);