CREATE TABLE IF NOT EXISTS Accounts (
    auth0_id VARCHAR(32),
    email VARCHAR(100) NOT NULL, 
    username VARCHAR(30) NOT NULL DEFAULT (SUBSTRING_INDEX(email, '@', 1)),
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_online TINYINT(1) DEFAULT 1,
    PRIMARY KEY (auth0_id),
    UNIQUE (email, username)
);